version: '3.7'

volumes:
  db: # mount it internally instead of a folder. it avoids file lock problems

services:
  app:
    env_file: ./.env
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: bash -c "npm install && npm run start:dev"
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
